/**
 * Author:  Kevin
 * Created: 15-mag-2017
 */

/*********************
*        DATI DB     *
*                    *
*  username: nerd    *
*  password: nerd    *
*                    *
*********************/


CREATE TABLE utente(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256) UNIQUE,
    cognome VARCHAR(256),
    urlfoto VARCHAR(1024),
    frase VARCHAR(1024),
    password VARCHAR(256) NOT NULL,
    nascita DATE
    gruppo INTEGER
    FOREIGN KEY(gruppo) REFERENCES gruppo(group_id);

CREATE TABLE posttype(
    type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMATY KEY,
    post_name VARCHAR(50));

CREATE TABLE post(
    post_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autore INTEGER,
    tipo INTEGER,
    content VARCHAR(1024),
    owner INTEGER,
    FOREIGN KEY (owner) REFERENCES utente(id),
    FOREIGN KEY (autore) REFERENCES utente(id),
    FOREIGN KEY (tipo) REFERENCES posttype(type_id));

CREATE TABLE gruppo(
    group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50));

CREATE TABLE hearts (
   follower INTEGER,
   FOREIGN KEY (follower) REFERENCES utente(id),
   followed INTEGER,
   FOREIGN KEY (followed) REFERENCES utente(id),
   PRIMARY KEY (follower, followed);

--Popolamento tabella UTENTE
INSERT INTO utente(id,nome,cognome,urlfoto,frase,password,nascita,gruppo)
VALUES(default,
        'Lorenzo',
        'Maioli',
        'img/maioli.jpg',
        'Felice di esser qui',
        'ciao',
        '1993-09-01',
        2);

INSERT INTO utente(id,nome,cognome,urlfoto,frase,password,nascita,gruppo)
VALUES(default,
        'Guido',
        'Vettel',
        'img/vettel.jpg',
        'Fantastico',
        'ehitu',
        '1996-07-05',
        3);

INSERT INTO utente(id,nome,cognome,urlfoto,frase,password,nascita,gruppo)
VALUES(default,
        'Fernando',
        'Rana',
        'img/rana.jpg',
        'ciao a tutti',
        'pasta',
        '1966-01-05',
        3);

INSERT INTO utente(id,nome,cognome,urlfoto,frase,password,nascita,gruppo)
VALUES(default,
        'Christan',
        'Vieri',
        'img/vieri.jpg',
        'Ciao invidiosi!',
        'bobogol',
        '1973-07-12',
        1);

INSERT INTO utente(id,nome,cognome,urlfoto,frase,password,nascita,gruppo)
VALUES(default,
        'Paolo',
        'Maldini',
        'img/maldini.jpg',
        'Forza Milan!',
        'champions',
        '1968-06-26',
        1);

INSERT INTO utente(id,nome,cognome,urlfoto,frase,password,nascita,gruppo)
VALUES(default,
        'Javier',
        'Zanetti',
        'img/zanetti.jpg',
        'Forza Inter!',
        'capitano',
        '1973-08-10',
        1);

INSERT INTO utente(id,nome,cognome,urlfoto,frase,password,nascita,gruppo)
VALUES(default,
        'Francesca',
        'Rossi',
        'img/rossi.jpg',
        'Carpe Diem',
        'ciao',
        '2003-04-01',
        2);

--Popolamento tabella POSTTYPE
INSERT INTO posttype (type_id,post_name)
VALUES(default,'TEXT');

INSERT INTO posttype (type_id,post_name)
VALUES(default,'IMAGE');

INSERT INTO posttype (type_id,post_name)
VALUES(default,'LINK');

--Popolamento tabella POST
INSERT INTO post (post_id,autore,tipo,content,owner)
VALUES(  default,
        1,
        1,
        'Sabato 29 aprile le autorità turche hanno bloccato Wikipedia',
        1);

INSERT INTO post (post_id,autore,tipo,content,owner)
VALUES(  default,
        2,
        2,
        'img/ferrari.jpg',
        2);

INSERT INTO post (post_id,autore,tipo,content,owner)
VALUES(  default,
        2,
        1,
        'Gli Articolo 31 sono stati un gruppo rap italiano, formatosi a Milano nel 1990 e composto da J-Ax e DJ Jad',
        2);

INSERT INTO post (post_id,autore,tipo,content,owner)
VALUES(  default,
        2,
        3,
        'www.google.com',
        2);

INSERT INTO post (post_id,autore,tipo,content,owner)
VALUES(  default,
        3,
        3,
        'www.intel.it',
        3);

INSERT INTO post (post_id,autore,tipo,content,owner)
VALUES(  default,
        4,
        1,
        'Ci si vede ad Ibiza per il torneo di footvolley',
        4);

INSERT INTO post (post_id,autore,tipo,content,owner)
VALUES(  default,
        5,
        3,
        'www.acmilan.com/it/paolo-maldini',
        5);

INSERT INTO post (post_id,autore,tipo,content,url,owner)
VALUES(  default,
        6,
        2,
        'Il giorno più bello della mia carriera',
        'img/inter.jpg',
        6);

INSERT INTO post (post_id,autore,tipo,content,owner)
VALUES(  default,
        7,
        1,
        'Ligabue è il mio artista preferito',
        7);

--Popolamento tabella GRUPPO
INSERT INTO gruppo(group_id,nome)
VALUE(default,'Fantacalcio');

INSERT INTO gruppo(group_id,nome)
VALUE(default,'Fans Club Ligabue');

INSERT INTO gruppo(group_id,nome)
VALUE(default,'Family');

--Popolamento tabella HEARTS
INSERT INTO hearts (follower, followed)
VALUES  (1, 7),
        (7, 1),
        (2, 3),
        (3, 2),
        (4, 5),
        (4, 6),
        (5, 4),
        (5, 6),
        (6, 4),
        (6, 5);

