/**
 * Author:  Kevin
 * Created: 15-mag-2017
 */

/*********************
*        DATI DB     *
*                    *
*  username: nerd    *
*  password: nerd    *
*                    *
*********************/


CREATE TABLE utente(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256) UNIQUE,
    cognome VARCHAR(256),
    urlfoto VARCHAR(1024),
    frase VARCHAR(1024),
    password VARCHAR(256) NOT NULL,
    nascita DATE
    gruppo INTEGER
    FOREIGN KEY(gruppo) REFERENCES gruppo(group_id);

CREATE TABLE posttype(
    type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMATY KEY,
    post_name VARCHAR(50));

CREATE TABLE post(
    post_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autore INTEGER,
    tipo INTEGER,
    content VARCHAR(1024),
    FOREIGN KEY (autore) REFERENCES utente(id),
    FOREIGN KEY (tipo) REFERENCES posttype(type_id));

--Popolamento tabella UTENTE
INSERT INTO utente(id,nome,cognome,urlfoto,frase,password)
VALUES(default,
        'Lorenzo',
        'Maioli',
        'img/maioli.jpg',
        'Felice di esser qui',
        'ciao');

INSERT INTO utente(id,nome,cognome,urlfoto,frase,password)
VALUES(default,
        'Guido',
        'Vettel',
        'img/vettel.jpg',
        'Fantastico',
        'ehitu');

INSERT INTO utente(id,nome,cognome,urlfoto,frase,password)
VALUES(default,
        'Fernando',
        'Rana',
        'img/rana.jpg',
        'ciao a tutti',
        'pasta');

--Popolamento tabella POSTTYPE
INSERT INTO posttype (type_id,post_name)
VALUES(default,'TEXT');

INSERT INTO posttype (type_id,post_name)
VALUES(default,'IMAGE');

INSERT INTO posttype (type_id,post_name)
VALUES(default,'LINK');

--Popolamento tabella POST
INSERT INTO post (post_id,autore,tipo,content)
VALUES(  default,
        1,
        1,
        'Sabato 29 aprile le autorità turche hanno bloccato Wikipedia');

INSERT INTO post (post_id,autore,tipo,content)
VALUES(  default,
        2,
        2,
        'img/ferrari.jpg');

INSERT INTO post (post_id,autore,tipo,content)
VALUES(  default,
        2,
        1,
        'Gli Articolo 31 sono stati un gruppo rap italiano, formatosi a Milano nel 1990 e composto da J-Ax e DJ Jad');

INSERT INTO post (post_id,autore,tipo,content)
VALUES(  default,
        2,
        3,
        'www.google.com');

INSERT INTO post (post_id,autore,tipo,content)
VALUES(  default,
        3,
        3,
        'www.intel.it');
